# Generated by Django 4.2.4 on 2023-08-21 21:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('participating_in_tournament', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childs_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('preferred_coach', models.CharField(blank=True, choices=[('Brandon', 'Brandon'), ('Vishal', 'Vishal'), ('Ansh', 'Ansh'), ('Ishan', 'Ishan'), ('Shravan', 'Shravan'), ('Yajat', 'Yajat')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('skills', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
